New-Item -ItemType Directory -Path "config", "controller", "model", "repositories", "views/auth", "views/artist", "views/admin", "views/player", "views/layout", "public/css", "public/js", "public/images", "utils"

New-Item -ItemType File -Path "index.php"
New-Item -ItemType File -Path "config/config.php", "config/database.php"
New-Item -ItemType File -Path "controller/AuthController.php", "controller/ArtistController.php", "controller/AdminController.php"
New-Item -ItemType File -Path "model/User.php", "model/Artist.php", "model/Admin.php", "model/Player.php", "model/Playlist.php", "model/Song.php"
New-Item -ItemType File -Path "repositories/UserRepository.php", "repositories/AdminRepository.php"
New-Item -ItemType File -Path "views/auth/login.php", "views/auth/register.php"
New-Item -ItemType File -Path "views/artist/dashboard.php"
New-Item -ItemType File -Path "views/admin/dashboard.php"
New-Item -ItemType File -Path "views/player/home.php"
New-Item -ItemType File -Path "views/layout/header.php", "views/layout/footer.php"
New-Item -ItemType File -Path "views/404.php", "views/500.php"
New-Item -ItemType File -Path "utils/Session.php", "utils/Validator.php"
